# Practical box size estimation from RFID interrogation traces using transfer learning 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Move to the directory where dataset_traces from RFID interrogation are placed
import os
os.chdir('/content/drive/My Drive/Colab Notebooks/_BOX_SIZE')

%pwd

Mounted at /content/drive


'/content/drive/My Drive/Colab Notebooks/_BOX_SIZE'

In [ ]:
# Bibliotecas necesarias
import numpy as np
import random
import os

# Configuramos matplotlib
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

%load_ext tensorboard

# Semilla fija para reproducibilidad
np.random.seed(1)

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [ ]:
import pandas
import pickle

def change_distro(X,t,samples):  
    newX = np.zeros(shape=[samples.sum(),X.shape[1]])
    newt = np.zeros(shape=[samples.sum(),])
    numsamples = 0
    for i in range(t.max()+1):
        aux = X[t==i]
        newX[numsamples:numsamples+samples[i]] = aux[:samples[i]]
        newt[numsamples:numsamples+samples[i]] = i
        numsamples += samples[i]
    
    newt = newt.astype(int)
    return newX,newt

def readdataset(id, maxsize=0, debug=False):
    picklefile = f'{id}/data.pickle'

    try:
        with open(picklefile, 'rb') as f:
            X, t = pickle.load(f)
            print(f'Datos ya disponibles de {picklefile}')
    
    except:
        index = pandas.read_csv(f'{id}/index.{id}.txt')
        index["numframes"] = index.framelst-index.frameini+1
        maxframes = index.numframes.max()
        frames = pandas.read_csv(f'{id}/frames.{id}.txt')
    
        if maxsize>0:
            SAMPLES = maxsize
        else:
            SAMPLES = len(index)
            
        if debug:
            print(f'Samples: {SAMPLES}')
            
        X = np.zeros(shape=[SAMPLES, 23]) 
        t = np.zeros(shape=[SAMPLES, ]) 
    
        for i in range(SAMPLES):
            if maxsize>0:
                batch = random.randint(0,SAMPLES-1)
            else:
                batch = i
            tagsread = index.iloc[batch].tagsread
            readtime = index.iloc[batch].readtime
            numframes = index.iloc[batch].numframes
            framebase = int(index.iloc[batch].frameini) 
            aux = frames.loc[framebase:framebase+numframes-1].values
            X[i,0] = tagsread
            X[i,1] = readtime
            X[i,2] = numframes
            X[i,3:8] = aux.mean(axis=0)
            X[i,8:13] = aux.std(axis=0)
            X[i,13:18] = aux.min(axis=0)
            X[i,18:23] = aux.max(axis=0)
            t[i] = index.iloc[batch].boxoriginal
            #X[batch,3:3+numframes*5] = frames.loc[framebase:framebase+numframes-1].values.ravel()
            if (debug) and ((i+1)%5000)==0:
                print(f'i: {i+1}, batch: {batch}, frames: {numframes}, framebase: {framebase}, t: {t[i]}, aux: {aux}')
        
            t = t.astype(int)
   
        with open(picklefile, 'wb') as f:
            pickle.dump([X, t], f)
    
        if debug: 
            frames.head(-1)
            
    return X,t

In [ ]:
import keras
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

import tensorflow as tf
from sklearn.metrics import confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from keras.callbacks import ModelCheckpoint
from keras.callbacks import EarlyStopping
from keras.callbacks import TensorBoard

def evalmodel(X,t,id,info='Full',debug=False):  
    modelname = f'{id}/model{info}.h5'
    
    if info=='Tags':
        X = X[:,0:1]
    elif info=='Basic':
        X = X[:,0:3]
    # 'Full' -> Toda la info
    
    X_train, X_test, t_train, t_test =  train_test_split(X, t, test_size=0.8)
    
    standard_transformer = Pipeline(steps=[('standard', StandardScaler())])
    minmax_transformer = Pipeline(steps=[('minmax', MinMaxScaler())])
    preprocessor = ColumnTransformer(
        remainder='passthrough', #passthough features not listed
        transformers=[
            ('std', standard_transformer , []),#slice(0,X.shape[1])),
            ('mm', minmax_transformer , slice(0,X.shape[1]))
        ])
    X_train = preprocessor.fit_transform(X_train)
    X_test = preprocessor.transform(X_test)
    model = keras.models.Sequential([
        keras.layers.Dense(100, activation="relu", input_shape=X_train.shape[1:]),
        keras.layers.Dense(50, activation="tanh"),
        keras.layers.Dense(int(t.max())+1, activation="sigmoid")
    ])
    
    try: 
        model = keras.models.load_model(modelname) # cargar modelo
    except:
        early_stopping_cb = EarlyStopping(patience=100, restore_best_weights=True)
        checkpoint_cb = ModelCheckpoint(modelname, save_best_only=True)
        tensorboard_cb = TensorBoard(f'{id}/log', histogram_freq=1)
        model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
        model.fit(X_train, t_train, epochs=50000
                  , validation_data=(X_test, t_test), batch_size=32, callbacks=[early_stopping_cb, checkpoint_cb, tensorboard_cb], verbose=0)
        model.save(modelname)
    
    precision = model.evaluate(X_test,t_test)[1]
    #y_test = model.predict_classes(X_test)
    y = np.argmax(model.predict(X_processed),axis=1)
    conf = confusion_matrix(list(map(int,t_test)), y_test)
    
    return precision, conf

In [ ]:
escenarios={'CGG','CGM','CGP','CMG','CMM','CMP','CPG','CPM','CPP','IGG','IGM','IGP','IMG','IMM','IMP','IPG','IPM','IPP','SGG','SGM','SGP','SMG','SMM','SMP','SPG','SPM','SPP'}
infoset={'Full','Basic','Tags'}

for info in infoset:
    for escenario in escenarios:
        # %tensorboard --logdir f'{escenario}/log'   -> Descomentar para ver la evolucion del entrenamiento
        print(f'Escenario: {escenario}, Info: {info}')
        X, t = readdataset(escenario)
        precision, conf = evalmodel(X,t,escenario,info)
        print(f'Accuracy: {precision*100:0.2f}%\nConfussion matrix:\n{conf}')

Escenario: CPG, Info: Full
500/500 [==============================] - 1s 1ms/step - loss: 1.1272 - accuracy: 0.5162


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 51.62%
Confussion matrix:
[[931  49   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [206 679 130   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  4 124 699 168   3   0   0   0   0   0   0   0   0   0   0   0]
 [  0   4 183 603 188  27   1   0   0   0   0   0   0   0   0   0]
 [  0   0  21 278 619  59  31   4   0   0   0   0   0   0   0   0]
 [  0   0   0  14 154 657 142  27   9   9   0   0   0   0   0   0]
 [  0   0   0   2 100 206 354 215 120  33   1   0   0   0   0   0]
 [  0   0   0   0  12  73 202 275 249 164  10   0   0   0   0   0]
 [  0   0   0   0   4  12 112 160 437 170  37   2   0   0   0   0]
 [  0   0   0   0   0  11  15  64 158 535 260  13   0   0   1   0]
 [  0   0   0   0   0   0   0   7  50 259 518 106   3   1   2   0]
 [  0   0   0   0   0   0   0   0   0   8 114 576 206  40  58   5]
 [  0   0   0   0   0   0   0   0   0   2  36 326 311  87 191  66]
 [  0   0   0   0   0   0   0   0   0   0  13 175 219  74 318 180]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 67.73%
Confussion matrix:
[[960  17   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [222 790  10   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  2  30 865 142   7   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0 221 687  39   2   8   0   0   0   0   0   0   0   0   0]
 [  0   0   8  52 856  16  44   9   2   0   0   0   0   0   0   0]
 [  0   0   0   1  26 931   8  45  14   0   0   0   0   0   0   0]
 [  0   0   0  10  64   5 822  46   6  47   0   0   0   0   0   0]
 [  0   0   0   0  20  15  35 560 252  43  35   0   0   0   0   0]
 [  0   0   0   0   7  12  10 146 770   4  34  15   0   1   0   2]
 [  0   0   0   0   0   0  45  61  24 655 134   1   0   1   0   0]
 [  0   0   0   0   0   1   2  44  50  99 801  44  12   1   0   1]
 [  0   0   0   0   0   0   0   0  24   0  88 411 135 208   7  69]
 [  0   0   0   0   0   0   0   0   7   0  47 152 287 354  79  73]
 [  0   0   0   0   0   0   0   0   3   0  17 128 127 430 136 188]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 84.48%
Confussion matrix:
[[1996    4    0    0    0    0    0    0]
 [   8 1850   96    0    0    0    0    0]
 [   0  183 1773   94    1    0    0    0]
 [   0    2  110 1806  111    4    0    0]
 [   0    0    0  138 1718   70   46    1]
 [   0    0    0    2  128 1689  130   19]
 [   0    0    0    0   67  103 1464  445]
 [   0    0    0    0   15   33  673 1221]]
Escenario: CPP, Info: Full
500/500 [==============================] - 0s 824us/step - loss: 0.0360 - accuracy: 0.9866


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.66%
Confussion matrix:
[[3991    1    0    0]
 [   0 3976   12    0]
 [   0   10 3847  119]
 [   0    0   72 3972]]
Escenario: SMP, Info: Full
500/500 [==============================] - 0s 804us/step - loss: 0.0080 - accuracy: 0.9974


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.74%
Confussion matrix:
[[3949    1    0    0]
 [   1 4022    8    0]
 [   0    3 3945   16]
 [   0    0   12 4043]]
Escenario: IGP, Info: Full
500/500 [==============================] - 0s 799us/step - loss: 2.0295e-04 - accuracy: 0.9999


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.99%
Confussion matrix:
[[3968    0    0    0]
 [   0 4059    0    0]
 [   0    0 4020    0]
 [   0    0    1 3952]]
Escenario: IMP, Info: Full
500/500 [==============================] - 0s 767us/step - loss: 0.0024 - accuracy: 0.9998


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.98%
Confussion matrix:
[[4007    2    0    0]
 [   0 3992    0    0]
 [   0    0 4065    2]
 [   0    0    0 3932]]
Escenario: IMG, Info: Full
500/500 [==============================] - 0s 854us/step - loss: 0.5054 - accuracy: 0.7941


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 79.41%
Confussion matrix:
[[1051   23    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [  80  927    4    0    0    1    0    0    0    0    0    0    0    0
     0    0]
 [   2   37  760  213    0    1    0    0    0    0    0    0    0    0
     0    0]
 [   0    1  182  808    3    1    0    0    0    0    0    0    0    0
     0    0]
 [   0    0    4   28  851    1  100    2    0    0    0    0    0    0
     0    0]
 [   0    0    0    0    0  989    0    0    2    0    0    0    0    0
     0    0]
 [   0    0    0    2  111    0  756  108    1    1    0    0    0    0
     0    0]
 [   0    0    0    0    6    0  158  690   18  150    1    0    0    0
     0    0]
 [   0    0    0    0    1    0    0   41  906   31   26    0    1    0
     0    0]
 [   0    0    0    0    0    0   12  195   46  568  211    0    0    0
     0    0]
 [   0    0    0    0    0    0    0   18   50  231  673    1    0    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 75.57%
Confussion matrix:
[[1952   14    0    0    0    0    0    0]
 [  24 1809  139    1    0    0    0    0]
 [   0  222 1362  424    2    0    0    0]
 [   0    3  296 1512  222    0    0    0]
 [   0    0    2  188 1542  235    4    0]
 [   0    0    0    4  284 1474  257   12]
 [   0    0    0    0    2  245 1179  659]
 [   0    0    0    0    0   59  611 1261]]
Escenario: SGM, Info: Full
500/500 [==============================] - 0s 825us/step - loss: 0.3449 - accuracy: 0.8537


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 85.37%
Confussion matrix:
[[1932    1    0    0    0    0    0    0]
 [  11 1829  129    0    0    0    0    0]
 [   0  152 1627  133    0    0    0    0]
 [   0    0  136 1796   81    6    0    0]
 [   0    0    0   66 1832  114    5    1]
 [   0    0    0    7  215 1807   29   10]
 [   0    0    0    0    3   65 1405  578]
 [   0    0    0    0    2   38  566 1424]]
Escenario: CGG, Info: Full
500/500 [==============================] - 0s 833us/step - loss: 1.1289 - accuracy: 0.5208


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 52.08%
Confussion matrix:
[[958  96   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [144 665 129   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  2  94 756 176  11   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2 181 553 263  24   2   0   0   0   0   0   0   0   0   0]
 [  0   1  17 186 644  56  79   4   0   0   0   0   0   0   0   0]
 [  0   0   0  36 144 683 101  50   0  11   0   0   0   0   0   0]
 [  0   0   0   2  66 199 350 262  80  23   0   0   0   0   0   0]
 [  0   0   0   0   9  80 183 278 221 171   8   0   0   0   0   0]
 [  0   0   0   0   2   6 119 204 413 182  47   0   0   0   0   0]
 [  0   0   0   0   0   7  10 112 134 506 232  22   0   0   0   0]
 [  0   0   0   0   0   0   1  13  63 243 545 123   8   0   0   0]
 [  0   0   0   0   0   0   0   0   0  10 123 647 130  34  66   2]
 [  0   0   0   0   0   0   0   0   0   0  34 421 199  75 247  29]
 [  0   0   0   0   0   0   0   0   0   0  14 253 207  95 342  93]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 73.62%
Confussion matrix:
[[976  35   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [118 882   5   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  16 809 171   4   0   0   0   0   0   0   0   0   0   0   0]
 [  0   1 221 786  12   0   2   0   0   0   0   0   0   0   0   0]
 [  0   0   2  15 903   1  65  21   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 998   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0   4  62   0 850   3   0  40   0   0   0   0   0   0]
 [  0   0   0   0  12   0   9 890  16  19  42   0   0   0   0   0]
 [  0   0   0   0   0   6   0  45 892   0  10  36   0   0   0   7]
 [  0   0   0   0   2   0  26  70   1 844  57   0   0   0   0   0]
 [  0   0   0   0   0   0   0  98  11  63 847   0   2   0   0   2]
 [  0   0   0   0   0   1   0   0  49   0   0 550 148  68  39 164]
 [  0   0   0   0   0   0   0   0  10   0   0 279 409 105 111  72]
 [  0   0   0   0   0   0   0   0   8   0   0 169 118 171 163 327]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 73.61%
Confussion matrix:
[[940  16   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [227 752  25   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1  48 832 163   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   4 202 677  88   0  15   0   0   0   0   0   0   0   0   0]
 [  0   0   3 139 775  14  25  19   0   0   0   0   0   0   0   0]
 [  0   0   0   0  17 995   4   1   1   1   0   0   0   0   0   0]
 [  0   0   0  12  58   6 750  94  53  38   1   0   0   0   0   0]
 [  0   0   0   0  21   9 149 647 136  26  45   0   0   0   0   0]
 [  0   0   0   0   2   0  71 104 726  71  34   1   0   0   0   0]
 [  0   0   0   0   0   4  54   8 141 662 141   7   0   0   0   0]
 [  0   0   0   0   0   0   0  22  59 108 777  22   7   0   0   0]
 [  0   0   0   0   0   0   0   0   5  10  32 515 305  55  58   0]
 [  0   0   0   0   0   0   0   0   1   1  28 184 607  50 111   2]
 [  0   0   0   0   0   0   0   0   0   0   3  61 114 380 406  15]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 86.26%
Confussion matrix:
[[2001    5    0    0    0    0    0    0]
 [  15 1860  126    0    0    0    0    0]
 [   0  177 1712   92    0    0    0    0]
 [   0    0   93 1827   84    8    0    0]
 [   0    0    1   55 1765  149    9    0]
 [   0    0    0    5  113 1881   27    5]
 [   0    0    0    0    6   23 1415  580]
 [   0    0    0    0    0    6  619 1341]]
Escenario: SGP, Info: Full
500/500 [==============================] - 0s 835us/step - loss: 0.0206 - accuracy: 0.9948


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.48%
Confussion matrix:
[[3921    8    0    0]
 [   0 3991    5    0]
 [   0   14 4037   21]
 [   0    0   35 3968]]
Escenario: IGM, Info: Full
500/500 [==============================] - 0s 807us/step - loss: 0.2470 - accuracy: 0.8956


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 89.56%
Confussion matrix:
[[1978    3    1    0    0    0    0    0]
 [   5 1903   92    1    0    0    0    0]
 [   0   98 1868   41    0    0    0    0]
 [   0    0   84 1932    4    2    0    0]
 [   0    0    0   13 1860  130    3    0]
 [   0    0    0    2  166 1766    1    0]
 [   0    0    0    0    2    1 1626  414]
 [   0    0    0    0    0    1  606 1397]]
Escenario: IPP, Info: Full
500/500 [==============================] - 0s 832us/step - loss: 0.0014 - accuracy: 0.9996


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.96%
Confussion matrix:
[[3861    0    0    0]
 [   0 4061    2    0]
 [   0    5 4058    0]
 [   0    0    0 4013]]
Escenario: IGG, Info: Full
500/500 [==============================] - 0s 798us/step - loss: 0.5693 - accuracy: 0.7559


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 75.59%
Confussion matrix:
[[ 996   14    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 101  889    2    1    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   1   43  777  127    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   0    3  218  782   34    0    0    0    0    0    0    0    0    0
     0    0]
 [   0    0    0   19  956    0   56    4    2    0    0    0    0    0
     0    0]
 [   0    0    0    0    0 1016    0    0    3    0    0    0    0    0
     0    0]
 [   0    0    0    0   34    0  641  266   26    1    2    0    0    0
     0    0]
 [   0    0    0    0    8    0  262  679   21    1   21    0    0    0
     0    0]
 [   0    0    0    0    0    0   27   27  643  188   66    0    1    0
     0    0]
 [   0    0    0    0    0    0   12   15  286  470  266    0    0    0
     0    0]
 [   0    0    0    0    0    0    5   11   59  169  811    0    3    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 52.20%
Confussion matrix:
[[940  89   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [134 687 123   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 105 769 132   4   0   0   0   0   0   0   0   0   0   0   0]
 [  0   3 240 485 194  21   1   0   0   0   0   0   0   0   0   0]
 [  0   0  27 247 607  53  42   8   0   0   0   0   0   0   0   0]
 [  0   0   1  31 139 723  74  65   4   6   0   0   0   0   0   0]
 [  0   0   0   4  96 234 208 312  75  30   0   0   0   0   0   0]
 [  0   0   0   0  19 112 106 391 242 138   9   0   0   0   0   0]
 [  0   0   0   0   7  16  58 272 433 194  44   0   0   0   0   0]
 [  0   0   0   0   0   9  10  81 150 480 280  22   1   0   0   0]
 [  0   0   0   0   0   3   0   6  47 220 563  90  18   7   1   0]
 [  0   0   0   0   0   0   0   0   0   7 129 440 244 110   1   7]
 [  0   0   0   0   0   0   0   0   0   1  32 233 349 313  35  65]
 [  0   0   0   0   0   0   0   0   0   0  12 121 237 389  55 212]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 76.53%
Confussion matrix:
[[1950   23    0    0    0    0    0    0]
 [   9 1897  123    0    0    0    0    0]
 [   0  218 1421  352    0    0    0    0]
 [   0    0  310 1448  185    2    0    0]
 [   0    0    0  157 1591  216    0    0]
 [   0    0    0    0  251 1577  229   37]
 [   0    0    0    0    0  239  912  845]
 [   0    0    0    0    0   74  485 1449]]
Escenario: CMP, Info: Full
500/500 [==============================] - 0s 836us/step - loss: 0.0378 - accuracy: 0.9865


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.65%
Confussion matrix:
[[4042    1    0    0]
 [   1 4101    9    0]
 [   0    8 3846  104]
 [   0    0   93 3795]]
Escenario: CGP, Info: Full
500/500 [==============================] - 0s 800us/step - loss: 0.0350 - accuracy: 0.9871


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.71%
Confussion matrix:
[[4058    4    0    0]
 [   0 4051    5    0]
 [   0   21 3819   75]
 [   0    0  101 3866]]
Escenario: SPP, Info: Full
500/500 [==============================] - 0s 883us/step - loss: 0.0130 - accuracy: 0.9956


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.56%
Confussion matrix:
[[3952    2    0    0]
 [   4 4054    5    0]
 [   0    3 3936   32]
 [   0    0   24 3988]]
Escenario: IPM, Info: Full
500/500 [==============================] - 0s 799us/step - loss: 0.2475 - accuracy: 0.8888


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 88.88%
Confussion matrix:
[[2010    0    0    0    0    0    0    0]
 [   4 1872  102    1    0    0    0    0]
 [   0  152 1835    7    0    0    0    0]
 [   0    0   15 1916   12   14    0    0]
 [   0    0    0   19 1829   55   73    1]
 [   0    0    0   22   29 1987    0    1]
 [   0    0    0    0   80    0 1303  643]
 [   0    0    0    0   14    0  536 1468]]
Escenario: CMM, Info: Full
500/500 [==============================] - 0s 789us/step - loss: 0.5414 - accuracy: 0.7572


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 75.72%
Confussion matrix:
[[2012   12    0    0    0    0    0    0]
 [  32 1830  148    0    0    0    0    0]
 [   0  194 1599  230    1    0    0    0]
 [   0    2  468 1326  181    0    0    0]
 [   0    0    2  189 1531  232    2    0]
 [   0    0    0    0  271 1433  284   54]
 [   0    0    0    0    1  240  995  739]
 [   0    0    0    0    0   43  561 1388]]
Escenario: SMG, Info: Full
500/500 [==============================] - 0s 829us/step - loss: 0.6240 - accuracy: 0.7407


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 74.07%
Confussion matrix:
[[913  75   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 94 868  18   3   4   0   0   0   0   0   0   0   0   0   0   0]
 [  2  69 705 186   4   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2 159 799  41   0  20   0   0   0   0   0   0   0   0   0]
 [  0   0   5  79 830   0  70  10   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 980   0   0   2   0   0   0   0   0   0   0]
 [  0   0   0  12  60   0 790  98  10  23   0   0   0   0   0   0]
 [  0   0   0   0  13   0 119 632 110  42  48   0   0   0   0   0]
 [  0   0   0   0   1   0  12 138 764  51  55   3   1   0   0   0]
 [  0   0   0   0   0   1  47  95  84 596 151   3   0   0   0   0]
 [  0   0   0   0   0   0   1  26  39 109 772  21   5   0   0   0]
 [  0   0   0   0   0   2   0   0   2   1  19 613 225 144  18   1]
 [  0   0   0   0   0   0   0   0   0   0   4 329 565 119  25   1]
 [  0   0   0   0   0   0   0   0   0   0   0  65  71 510 319  33]
 [  0   0   0   0   0   1 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 89.72%
Confussion matrix:
[[2065    0    0    0    3    0    0    0]
 [   3 1876   86    0    4    0    0    0]
 [   0  142 1804   14    2    0    0    0]
 [   0    1   33 2020    8    9    0    0]
 [   0    0    0    8 1885  116    2    0]
 [   0    0    0    6   95 1848    1    1]
 [   0    0    0    0    0    0 1560  474]
 [   0    0    0    0    1    0  633 1300]]
Escenario: CPG, Info: Basic
Datos ya disponibles de CPG/data.pickle
500/500 [==============================] - 0s 811us/step - loss: 1.1590 - accuracy: 0.4944


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 49.44%
Confussion matrix:
[[963   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [517 446  22   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 17 250 566 163   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   6 224 610 166  11   1   0   0   0   0   0   0   0   0   0]
 [  0   1  17 311 441 175  52   1   0   0   0   0   0   0   0   0]
 [  0   0   0  46 165 580 191  27   9   1   0   0   0   0   0   0]
 [  0   0   0   3  44 206 460 162 138  22   0   0   0   0   0   0]
 [  0   0   0   0   1  86 220 223 340 118   9   0   0   0   0   0]
 [  0   0   0   0   2  10 122 177 501 125  36   0   0   0   0   0]
 [  0   0   0   0   0   7  12  77 273 433 214  12   0   0   0   0]
 [  0   0   0   0   0   2   0   8 106 274 452 137   5   0   0   0]
 [  0   0   0   0   0   0   0   0   1   6 108 562 225   0  99   5]
 [  0   0   0   0   0   0   0   0   0   0  21 354 339   0 265  58]
 [  0   0   0   0   0   0   0   0   0   0   6 178 284   1 386 145]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 50.30%
Confussion matrix:
[[954   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [555 431  62   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 16 167 669 190   3   0   0   0   0   0   0   0   0   0   0   0]
 [  0   5 189 532 253   0   2   0   0   0   0   0   0   0   0   0]
 [  0   0  13 245 648   3  88   1   0   0   0   0   0   0   0   0]
 [  0   0   1  10 213 517 271  11   4   0   0   0   0   0   0   0]
 [  0   0   0   2 102   1 666 161  18  33   1   0   0   0   0   0]
 [  0   0   0   0  13   4 386 299  62 153  11   1   0   0   0   0]
 [  0   0   0   0   2  11 123 173 392 195  35  35   0   0   0   1]
 [  0   0   0   0   0   0  28 135  28 457 255  11   0   0   0   0]
 [  0   0   0   0   0   0   3  30  32 225 618 101  23   8   0   0]
 [  0   0   0   0   0   0   0   0  38   3 129 337 196 211  37  27]
 [  0   0   0   0   0   0   0   0   8   0  50 146 249 369 149  49]
 [  0   0   0   0   0   0   0   0  11   0  17 159 193 349 230  93]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 77.64%
Confussion matrix:
[[2007    6    0    0    0    0    0    0]
 [  31 1737  161    0    0    0    0    0]
 [   0  156 1519  356    1    0    0    0]
 [   0    1  310 1535  146    0    0    0]
 [   0    0    0  142 1626  161   89    1]
 [   0    0    0    0  235 1485  229   23]
 [   0    0    0    0  103  128 1280  558]
 [   0    0    0    0   11   48  679 1236]]
Escenario: CPP, Info: Basic
Datos ya disponibles de CPP/data.pickle
500/500 [==============================] - 0s 827us/step - loss: 0.0382 - accuracy: 0.9863


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.63%
Confussion matrix:
[[4001    0    0    0]
 [   0 3964   12    0]
 [   0   12 3821  100]
 [   0    0   95 3995]]
Escenario: SMP, Info: Basic
Datos ya disponibles de SMP/data.pickle
500/500 [==============================] - 0s 798us/step - loss: 0.0305 - accuracy: 0.9894


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.94%
Confussion matrix:
[[3997    0    0    0]
 [   5 4016   12    0]
 [   0   12 3842   60]
 [   0    0   80 3976]]
Escenario: IGP, Info: Basic
Datos ya disponibles de IGP/data.pickle
500/500 [==============================] - 0s 833us/step - loss: 0.0233 - accuracy: 0.9915


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.15%
Confussion matrix:
[[3996    0    0    0]
 [   0 4035   10    0]
 [   0   12 3966   53]
 [   0    0   61 3867]]
Escenario: IMP, Info: Basic
Datos ya disponibles de IMP/data.pickle
500/500 [==============================] - 0s 853us/step - loss: 0.0159 - accuracy: 0.9941


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.41%
Confussion matrix:
[[4010    1    0    0]
 [   4 4034   14    0]
 [   0   11 3948   26]
 [   0    0   38 3914]]
Escenario: IMG, Info: Basic
Datos ya disponibles de IMG/data.pickle
500/500 [==============================] - 0s 801us/step - loss: 0.8523 - accuracy: 0.6232


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 62.32%
Confussion matrix:
[[1019   21    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 339  548   96    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   8  127  702  124    7    0    0    0    0    0    0    0    0    0
     0    0]
 [   0    6  260  437  304    0    2    0    0    0    0    0    0    0
     0    0]
 [   0    0   29  213  616    0  108    0    0    0    0    0    0    0
     0    0]
 [   0    0    0    1    3  993    1    6    0    0    0    0    0    0
     0    0]
 [   0    0    0    1  106    0  712   86   37   18    0    0    0    0
     0    0]
 [   0    0    0    0    5   11  219  381  308   93   19    0    0    0
     0    0]
 [   0    0    0    0    1    4  117  240  435  167   72    0    0    0
     0    0]
 [   0    0    0    0    0    0   57   87  253  412  236    1    0    0
     0    0]
 [   0    0    0    0    0    0    2   11   82  158  672   33   17    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 74.99%
Confussion matrix:
[[1914    9    0    0    0    0    0    0]
 [  31 1794  214    0    0    0    0    0]
 [   0  173 1529  323    1    0    0    0]
 [   0    1  354 1487  149    1    0    0]
 [   0    0    1  267 1475  258    0    0]
 [   0    0    0    1  261 1473  291   14]
 [   0    0    0    0    0  341 1104  624]
 [   0    0    0    0    0   74  615 1221]]
Escenario: SGM, Info: Basic
Datos ya disponibles de SGM/data.pickle
500/500 [==============================] - 0s 799us/step - loss: 0.5436 - accuracy: 0.7586


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 75.86%
Confussion matrix:
[[1925   10    0    0    0    0    0    0]
 [  17 1829  131    0    0    0    0    0]
 [   0  253 1467  210    1    0    0    0]
 [   0    5  464 1406  192    0    0    0]
 [   0    0    0  203 1602  224    3    0]
 [   0    0    0    1  307 1505  242   15]
 [   0    0    0    0    2  278 1116  600]
 [   0    0    0    0    0   60  645 1287]]
Escenario: CGG, Info: Basic
Datos ya disponibles de CGG/data.pickle
500/500 [==============================] - 0s 777us/step - loss: 1.1661 - accuracy: 0.4892


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 48.92%
Confussion matrix:
[[1039    3    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 503  426   30    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [  15  246  622  153    5    0    0    0    0    0    0    0    0    0
     0    0]
 [   0   10  223  447  315   16    0    0    0    0    0    0    0    0
     0    0]
 [   0    1   23  153  552  210   51    0    1    0    0    0    0    0
     0    0]
 [   0    0    1   11  196  482  298   19   27    1    0    0    0    0
     0    0]
 [   0    0    0    3   31  216  464   67  153   19    0    0    0    0
     0    0]
 [   0    0    0    0    3   53  329   98  305  158    5    0    0    0
     0    0]
 [   0    0    0    0    0    9  171  119  364  280   30    0    0    0
     0    0]
 [   0    0    0    0    0    1   25   50  192  546  217   14    0    0
     0    0]
 [   0    0    0    0    0    0    3    8   29  325  518  124    3    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 59.35%
Confussion matrix:
[[986   6   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [525 461  61   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 13 144 741 105   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   2 237 577 206   0   4   0   0   0   0   0   0   0   0   0]
 [  0   0  16 242 700   0  83   1   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 986   0   0   4   0   0   0   0   0   0   0]
 [  0   0   0   3 122   0 680  78   0  47   0   0   0   0   0   0]
 [  0   0   0   1  14   0 191 630   7 132  35   0   0   0   0   0]
 [  0   0   0   0   1   9   8  73 757  23  19 110   1   0   0   0]
 [  0   0   0   0   0   0  47 165   1 593 203   0   0   0   0   0]
 [  0   0   0   0   0   0   4  51   2 202 757   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  77   0   0 623 187  21  47  53]
 [  0   0   0   0   0   0   0   0  13   0   0 270 447  45 137  65]
 [  0   0   0   0   0   0   0   0  18   0   0 330 322  42 153  59]
 [  0   0   0   0   0   1 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 50.47%
Confussion matrix:
[[963   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [534 455  17   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 13 225 618 143  13   0   0   0   0   0   0   0   0   0   0   0]
 [  1   9 205 479 265  22   0   0   0   0   0   0   0   0   0   0]
 [  0   0  16 179 585 140  30   0   0   0   0   0   0   0   0   0]
 [  0   0   0  26 241 515 221  25  16   2   0   0   0   0   0   0]
 [  0   0   0   4  52 275 413  99 140  26   0   0   0   0   0   0]
 [  0   0   0   0   6  83 296 187 313 120   3   0   0   0   0   0]
 [  0   0   0   0   1  17 174 134 521 156  24   2   0   0   0   0]
 [  0   0   0   0   0   2  22  74 229 456 212  14   0   0   0   0]
 [  0   0   0   0   0   0   1  10  63 294 481 108   6   2   0   0]
 [  0   0   0   0   0   0   0   0   2  13 142 504 259  34  63  10]
 [  0   0   0   0   0   0   0   0   0   2  27 286 332  96 189  56]
 [  0   0   0   0   0   0   0   0   0   0   7 158 241  97 345 153]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 75.84%
Confussion matrix:
[[2017    6    0    0    0    0    0    0]
 [  26 1847  130    0    0    0    0    0]
 [   0  231 1449  317    0    0    0    0]
 [   0    4  353 1439  196    0    0    0]
 [   0    0    1  185 1555  320    0    0]
 [   0    0    0    2  231 1511  224   20]
 [   0    0    0    0    1  286 1013  685]
 [   0    0    0    0    0   65  587 1299]]
Escenario: SGP, Info: Basic
Datos ya disponibles de SGP/data.pickle
500/500 [==============================] - 0s 839us/step - loss: 0.0345 - accuracy: 0.9874


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.74%
Confussion matrix:
[[3955    0    0    0]
 [   1 3979   13    0]
 [   0   13 3967   87]
 [   0    0   88 3897]]
Escenario: IGM, Info: Basic
Datos ya disponibles de IGM/data.pickle
500/500 [==============================] - 0s 838us/step - loss: 0.4847 - accuracy: 0.7853


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 78.53%
Confussion matrix:
[[1980    5    0    0    0    0    0    0]
 [  20 1814  163    0    0    0    0    0]
 [   0  190 1482  301    0    0    0    0]
 [   0    2  305 1474  203    0    0    0]
 [   0    0    1  172 1678  148    0    0]
 [   0    0    0    0  185 1578  204   16]
 [   0    0    0    0    2  237 1249  572]
 [   0    0    0    0    0   54  654 1311]]
Escenario: IPP, Info: Basic
Datos ya disponibles de IPP/data.pickle
500/500 [==============================] - 0s 826us/step - loss: 0.0057 - accuracy: 0.9984


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 99.84%
Confussion matrix:
[[3926    0    0    0]
 [   1 4041   10    0]
 [   0   15 4014    0]
 [   0    0    0 3993]]
Escenario: IGG, Info: Basic
Datos ya disponibles de IGG/data.pickle
500/500 [==============================] - 0s 842us/step - loss: 0.9853 - accuracy: 0.5731


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 57.31%
Confussion matrix:
[[1012    1    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 518  449   14    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [  16  326  410  190    2    0    0    0    0    0    0    0    0    0
     0    0]
 [   0   24  153  657  195    0    2    0    0    0    0    0    0    0
     0    0]
 [   0    0   15  323  626    0   91    0    0    0    0    0    0    0
     0    0]
 [   0    0    0   17   54  801   37   64    1    2    3    0    0    0
     0    0]
 [   0    0    0    3  106   26  658   97   66    5    0    0    0    0
     0    0]
 [   0    0    0    0    4   73  237  424  153   94    7    0    0    0
     0    0]
 [   0    0    0    0    2   22  206  270  246  205   26    0    0    0
     0    0]
 [   0    0    0    0    0   10   28  142  156  432  277   17    0    0
     0    0]
 [   0    0    0    0    0    1    0   36   22  220  648  138    6    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 49.59%
Confussion matrix:
[[1036    1    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 486  473   25    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   6  264  606  110    2    0    0    0    0    0    0    0    0    0
     0    0]
 [   0    6  254  456  208   15    1    0    0    0    0    0    0    0
     0    0]
 [   0    0   37  217  525  160   22    2    0    0    0    0    0    0
     0    0]
 [   0    0    0   22  270  479  180   88    1    1    0    0    0    0
     0    0]
 [   0    0    0    4   54  246  234  355   48    4    1    0    0    0
     0    0]
 [   0    0    0    0    8   74  141  479  189   89   17    1    0    0
     0    0]
 [   0    0    0    0    2   22   66  379  286  173   73    3    0    0
     0    0]
 [   0    0    0    0    0    5    8  117  214  335  329   23    0    0
     0    0]
 [   0    0    0    0    0    1    0    9   58  145  581  191    8    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 76.00%
Confussion matrix:
[[1919   21    0    0    0    0    0    0]
 [  10 1877  130    0    0    0    0    0]
 [   0  226 1465  284    0    0    0    0]
 [   0    2  396 1403  185    1    0    0]
 [   0    0    0  216 1537  241    1    0]
 [   0    0    0    0  214 1621  221   12]
 [   0    0    0    0    1  300 1032  707]
 [   0    0    0    0    0   66  609 1303]]
Escenario: CMP, Info: Basic
Datos ya disponibles de CMP/data.pickle
500/500 [==============================] - 0s 787us/step - loss: 0.0364 - accuracy: 0.9863


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.63%
Confussion matrix:
[[4004    0    0    0]
 [   1 4104    8    0]
 [   0    9 3837   96]
 [   0    0  105 3836]]
Escenario: CGP, Info: Basic
Datos ya disponibles de CGP/data.pickle
500/500 [==============================] - 0s 823us/step - loss: 0.0377 - accuracy: 0.9862


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.62%
Confussion matrix:
[[4067    0    0    0]
 [   4 4007   21    0]
 [   0   11 3815   84]
 [   0    0  100 3891]]
Escenario: SPP, Info: Basic
Datos ya disponibles de SPP/data.pickle
500/500 [==============================] - 0s 801us/step - loss: 0.0322 - accuracy: 0.9887


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.87%
Confussion matrix:
[[3996    1    0    0]
 [   0 4064    8    0]
 [   0   11 3824   82]
 [   0    0   78 3936]]
Escenario: IPM, Info: Basic
Datos ya disponibles de IPM/data.pickle
500/500 [==============================] - 0s 838us/step - loss: 0.3645 - accuracy: 0.8401


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 84.01%
Confussion matrix:
[[2070    6    0    0    0    0    0    0]
 [  28 1820  127    0    0    0    0    0]
 [   0  132 1632  237    0    0    0    0]
 [   0    0  224 1722   34   13    0    0]
 [   0    0    1   77 1609   96  158    2]
 [   0    0    0   11   55 1902    0    1]
 [   0    0    0    0  182    0 1289  560]
 [   0    0    0    0   18    0  595 1399]]
Escenario: CMM, Info: Basic
Datos ya disponibles de CMM/data.pickle
500/500 [==============================] - 0s 822us/step - loss: 0.5376 - accuracy: 0.7634


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 76.34%
Confussion matrix:
[[1965   10    0    0    0    0    0    0]
 [  32 1821  171    0    0    0    0    0]
 [   0  182 1514  298    2    0    0    0]
 [   0    2  359 1461  173    0    0    0]
 [   0    0    0  222 1576  172    5    0]
 [   0    0    0    0  313 1426  292   19]
 [   0    0    0    0    3  262 1094  606]
 [   0    0    0    0    1   52  608 1359]]
Escenario: SMG, Info: Basic
Datos ya disponibles de SMG/data.pickle
500/500 [==============================] - 0s 825us/step - loss: 1.0737 - accuracy: 0.5305


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 53.05%
Confussion matrix:
[[995   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [600 392  31   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 29 233 558 171   3   0   0   0   0   0   0   0   0   0   0   0]
 [  0   5 172 594 186   1   2   0   0   0   0   0   0   0   0   0]
 [  0   1  18 302 571  19  56   2   0   0   0   0   0   0   0   0]
 [  0   0   0  16 226 537 192  34   2   0   0   0   0   0   0   0]
 [  0   0   0   2 136  59 481 243  45  24   1   0   0   0   0   0]
 [  0   0   0   0  25  18 206 401 158 125  17   0   0   0   0   0]
 [  0   0   0   0   1   1 111 353 261 222  66   0   0   0   0   0]
 [  0   0   0   0   1   0  13 109 164 352 317  15   0   0   0   0]
 [  0   0   0   0   0   0   1  14  39 183 608 135   9   1   0   0]
 [  0   0   0   0   0   0   0   1   0   0 120 505 238 132  27   8]
 [  0   0   0   0   0   0   0   0   0   0  16 268 339 284  79  49]
 [  0   0   0   0   0   0   0   0   0   0  11 138 207 307 218 121]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 78.98%
Confussion matrix:
[[2093    8    0    0    0    0    0    0]
 [  26 1765  170    0    0    0    0    0]
 [   0  188 1504  257    0    0    0    0]
 [   0    5  266 1632  166    0    0    0]
 [   0    0    0  177 1552  299    0    0]
 [   0    0    0    1  200 1603  128    5]
 [   0    0    0    0    1  154 1287  579]
 [   0    0    0    0    0   33  724 1177]]
Escenario: CPG, Info: Tags
Datos ya disponibles de CPG/data.pickle
500/500 [==============================] - 0s 813us/step - loss: 1.2127 - accuracy: 0.4663


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 46.63%
Confussion matrix:
[[960   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [872 148   8   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 96 306 493 107   0   0   0   0   0   0   0   0   0   0   0   0]
 [  1  18 287 548 148  32   1   0   0   0   0   0   0   0   0   0]
 [  0   1  32 311 323 320  30   0   0   0   0   0   0   0   0   0]
 [  0   0   1  57 181 511 220  22   2   1   0   0   0   0   0   0]
 [  0   0   1   1  34 236 459 240  19  28   1   0   0   0   0   0]
 [  0   0   0   0   2  55 283 398  46 168  12   0   0   0   0   0]
 [  0   0   0   0   1   8 133 373  60 324  60   2   0   0   0   0]
 [  0   0   0   0   0   2  34 192  61 476 266  15   0   0   0   0]
 [  0   0   0   0   0   0   4  30  13 294 468 131   7   0   0   0]
 [  0   0   0   0   0   0   0   1   0   2 119 477 197 145  47  16]
 [  0   0   0   0   0   0   0   0   0   1  32 294 216 234 112 123]
 [  0   0   0   0   0   0   0   0   0   0   8 164 167 228 155 261]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 42.64%
Confussion matrix:
[[996   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [752 272  17   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 44 360 444 177   3   0   0   0   0   0   0   0   0   0   0   0]
 [  0  19 200 521 244   0   2   0   0   0   0   0   0   0   0   0]
 [  0   0  15 252 641  37  56   1   0   0   0   0   0   0   0   0]
 [  0   4  50 267 411  55 217  17   6   0   0   0   0   0   0   0]
 [  0   0   0   2 103  43 549 177  85  27   1   0   0   0   0   0]
 [  0   0   0   0  15   6 313 215 239 139  14   0   0   0   0   0]
 [  0   0   0   0   6   3 166 209 290 257  38   0   0   0   0   0]
 [  0   0   0   0   0   0  18  49 141 434 240  27   2   0   0   0]
 [  0   0   0   0   0   0   0   7  48 246 492 198  56   0   0   0]
 [  0   0   0   0   0   0   0   3  10  96 283 229 278  51   6   7]
 [  0   0   0   0   0   0   0   0   1  19 156 210 375 155  18  51]
 [  0   0   0   0   0   0   0   0   3  49 188 185 264 194  38 116]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 69.31%
Confussion matrix:
[[2034    5    0    0    0    0    0    0]
 [  32 1808  114    0    0    0    0    0]
 [   0  213 1490  307    1    0    0    0]
 [   0    2  410 1442  164    0    0    0]
 [   0    0    0  260 1427  290    6    0]
 [   0    0    0    0  263 1113  488  113]
 [   0    0    0    0   93  629  510  841]
 [   0    0    0    0    9  256  414 1266]]
Escenario: CPP, Info: Tags
Datos ya disponibles de CPP/data.pickle
500/500 [==============================] - 0s 829us/step - loss: 0.0413 - accuracy: 0.9853


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.53%
Confussion matrix:
[[4004    0    0    0]
 [   0 4015   15    0]
 [   0   17 3829   99]
 [   0    0  104 3917]]
Escenario: SMP, Info: Tags
Datos ya disponibles de SMP/data.pickle
500/500 [==============================] - 0s 829us/step - loss: 0.0355 - accuracy: 0.9869


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.69%
Confussion matrix:
[[3966    1    0    0]
 [   0 3971   13    0]
 [   0   12 3852   87]
 [   0    0   96 4002]]
Escenario: IGP, Info: Tags
Datos ya disponibles de IGP/data.pickle
500/500 [==============================] - 0s 782us/step - loss: 0.0352 - accuracy: 0.9859


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.59%
Confussion matrix:
[[3944    0    0    0]
 [   0 4048   20    0]
 [   0   13 3974   98]
 [   0    0   94 3809]]
Escenario: IMP, Info: Tags
Datos ya disponibles de IMP/data.pickle
500/500 [==============================] - 0s 802us/step - loss: 0.0371 - accuracy: 0.9866


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.66%
Confussion matrix:
[[4017    1    0    0]
 [   0 4035   20    0]
 [   0   14 3907   86]
 [   0    0   93 3827]]
Escenario: IMG, Info: Tags
Datos ya disponibles de IMG/data.pickle
500/500 [==============================] - 0s 833us/step - loss: 1.2086 - accuracy: 0.4609


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 46.09%
Confussion matrix:
[[1042    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 745  283    4    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [  48  467  300  176    4    0    0    0    0    0    0    0    0    0
     0    0]
 [   0   69  157  522  196   39    1    0    0    0    0    0    0    0
     0    0]
 [   0    1   21  224  326  337   59    0    0    0    0    0    0    0
     0    0]
 [   0    0    0   70  184  477  228   11    3    0    0    0    0    0
     0    0]
 [   0    0    0    0    9  176  490  163   99   22    1    0    0    0
     0    0]
 [   0    0    0    0    0   38  270  262  299  146    6    0    0    0
     0    0]
 [   0    0    0    0    0    7  151  189  325  343   42    0    0    0
     0    0]
 [   0    0    0    0    0    0   25   78  177  509  231   14    0    0
     0    0]
 [   0    0    0    0    0    0    0    7   39  288  476  143    4    1
     1    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 74.59%
Confussion matrix:
[[1966    0    0    0    0    0    0    0]
 [  87 1775  123    0    0    0    0    0]
 [   0  234 1460  289    2    0    0    0]
 [   0    2  386 1339  262    0    0    0]
 [   0    0    4  166 1494  332    1    0]
 [   0    0    0    0  249 1416  374   12]
 [   0    0    0    0    1  252 1163  685]
 [   0    0    0    0    0   47  611 1268]]
Escenario: SGM, Info: Tags
Datos ya disponibles de SGM/data.pickle
500/500 [==============================] - 0s 844us/step - loss: 0.5570 - accuracy: 0.7497


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 74.97%
Confussion matrix:
[[1930    5    0    0    0    0    0    0]
 [  24 1854  136    0    0    0    0    0]
 [   0  233 1322  375    1    0    0    0]
 [   0    4  304 1511  203    0    0    0]
 [   0    0    0  182 1562  293    1    0]
 [   0    0    0    1  324 1416  280   18]
 [   0    0    0    0    2  307 1000  733]
 [   0    0    0    0    0   63  516 1400]]
Escenario: CGG, Info: Tags
Datos ya disponibles de CGG/data.pickle
500/500 [==============================] - 0s 878us/step - loss: 1.1747 - accuracy: 0.4823


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 48.23%
Confussion matrix:
[[1014    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 692  254    9    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [  45  381  453  167    0    0    0    0    0    0    0    0    0    0
     0    0]
 [   0   20  182  550  230   14    0    0    0    0    0    0    0    0
     0    0]
 [   0    2   17  246  521  233   12    2    0    0    0    0    0    0
     0    0]
 [   0    0    1   25  232  526  169   58    6    0    0    0    0    0
     0    0]
 [   0    0    0    3   34  330  311  218   74   14    1    0    0    0
     0    0]
 [   0    0    0    0    4   95  247  257  253  121   13    0    0    0
     0    0]
 [   0    0    0    0    0   30  121  237  254  252   64    0    0    0
     0    0]
 [   0    0    0    0    0    4   16   74  203  394  308   16    0    0
     0    0]
 [   0    0    0    0    0    0    3    8   52  199  596  135    9    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 38.84%
Confussion matrix:
[[985   2   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [547 420  69   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 12 140 682 147   4   5   0   0   0   0   0   0   0   0   0   0]
 [  0   4 194 487 265  77   4   0   0   0   0   0   0   0   0   0]
 [  0   0  21 168 673  71 100   1   0   0   0   0   0   0   0   0]
 [  0   0 137 394 348 103   8   0   0   0   0   0   0   0   0   0]
 [  0   0   0   3 115   0 581 143  62  16   0   0   0   0   0   0]
 [  0   0   0   0  18   0 367 262 216 155   5   0   0   0   0   0]
 [  0   0   0   0   7   0 229 233 224 262  31   1   0   0   0   3]
 [  0   0   0   0   0   0  39  73 163 436 166  24   0   0  48  46]
 [  0   0   0   0   0   0   3  13  44 288 232  57   0   0 259 123]
 [  0   0   0   0   0   0   2   3  20 207 233  67   0   0 320 168]
 [  0   0   0   0   0   0   0   0   0  41 100  23   0   0 699 110]
 [  0   0   0   0   0   0   0   1   3  74 137  31   0   0 589 122]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 48.26%
Confussion matrix:
[[963   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [712 278   5   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 34 355 537 101   8   0   0   0   0   0   0   0   0   0   0   0]
 [  3  29 260 460 214  31   0   0   0   0   0   0   0   0   0   0]
 [  0   0  25 213 403 296  16   2   0   0   0   0   0   0   0   0]
 [  0   0   1  32 145 646 145  60   7   0   0   0   0   0   0   0]
 [  0   0   0   2  21 362 268 219 117  16   0   0   0   0   0   0]
 [  0   0   0   0   1  98 175 290 296 135   5   0   0   0   0   0]
 [  0   0   0   0   0  31  96 216 362 261  34   0   0   0   0   0]
 [  0   0   0   0   0   3  13  63 232 443 226  24   0   0   0   0]
 [  0   0   0   0   0   1   0   5  49 285 468 166   5   0   0   0]
 [  0   0   0   0   0   0   0   0   0  10 118 534 212  72  67   3]
 [  0   0   0   0   0   0   0   0   0   2  18 329 270 164 206  37]
 [  0   0   0   0   0   0   0   0   0   0   3 170 193 161 294 153]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 74.89%
Confussion matrix:
[[2061    1    0    0    0    0    0    0]
 [  70 1763  142    0    0    0    0    0]
 [   0  213 1396  396    1    0    0    0]
 [   0    2  329 1463  228    1    0    0]
 [   0    0    0  166 1492  341    0    0]
 [   0    0    0    1  242 1448  293   17]
 [   0    0    0    0    1  276 1075  625]
 [   0    0    0    0    0   54  641 1262]]
Escenario: SGP, Info: Tags
Datos ya disponibles de SGP/data.pickle
500/500 [==============================] - 0s 813us/step - loss: 0.0369 - accuracy: 0.9864


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.64%
Confussion matrix:
[[3947    0    0    0]
 [   1 3949   18    0]
 [   0   13 3931   91]
 [   0    0   95 3955]]
Escenario: IGM, Info: Tags
Datos ya disponibles de IGM/data.pickle
500/500 [==============================] - 0s 812us/step - loss: 0.5519 - accuracy: 0.7499


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 74.99%
Confussion matrix:
[[1988    4    0    0    0    0    0    0]
 [  22 1864  130    0    0    0    0    0]
 [   0  243 1501  275    0    0    0    0]
 [   0    0  398 1384  167    0    0    0]
 [   0    0    0  242 1502  253    1    0]
 [   0    0    0    0  300 1312  343    6]
 [   0    0    0    0    2  229 1194  608]
 [   0    0    0    0    0   48  729 1255]]
Escenario: IPP, Info: Tags
Datos ya disponibles de IPP/data.pickle
500/500 [==============================] - 0s 804us/step - loss: 0.1512 - accuracy: 0.9354


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 93.54%
Confussion matrix:
[[3938    0    0    0]
 [   1 4014   16    0]
 [   0   13 3614  454]
 [   0    0  550 3400]]
Escenario: IGG, Info: Tags
Datos ya disponibles de IGG/data.pickle
500/500 [==============================] - 0s 831us/step - loss: 1.1834 - accuracy: 0.4815


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 48.15%
Confussion matrix:
[[976   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [700 271  11   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [ 39 341 445 138   6   0   0   0   0   0   0   0   0   0   0   0]
 [  0  27 198 540 232  24   0   0   0   0   0   0   0   0   0   0]
 [  0   0  18 260 516 228  14   3   0   0   0   0   0   0   0   0]
 [  0   0   0  23 215 486 166 105   5   0   1   0   0   0   0   0]
 [  0   0   0   2  47 250 246 349  56  16   1   0   0   0   0   0]
 [  0   0   0   0   3  67 140 446 247  95  14   0   0   0   0   0]
 [  0   0   0   0   0  33  65 306 274 231  47   0   0   0   0   0]
 [  0   0   0   0   0   4   9 103 200 456 267  13   0   0   0   0]
 [  0   0   0   0   0   0   0  18  59 279 603 120   7   0   0   0]
 [  0   0   0   0   0   0   0   0   0  11 165 398 332  33  22  13]
 [  0   0   0   0   0   0   0   0   0   1  41 236 465  80 127  76]
 [  0   0   0   0   0   0   0   0   0   0   4 111 365 114 171 195]
 [  0   0   0   0   0   0 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 48.90%
Confussion matrix:
[[1034    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 664  285    6    1    0    0    0    0    0    0    0    0    0    0
     0    0]
 [  39  367  429  153    3    0    0    0    0    0    0    0    0    0
     0    0]
 [   0   16  190  510  202   27    1    0    0    0    0    0    0    0
     0    0]
 [   0    1   24  224  464  233   14    2    0    0    0    0    0    0
     0    0]
 [   0    0    1   28  219  581  158   62    2    1    0    0    0    0
     0    0]
 [   0    0    0    3   35  326  250  256   68    4    1    0    0    0
     0    0]
 [   0    0    0    0    6  103  173  389  247  108   10    0    0    0
     0    0]
 [   0    0    0    0    2   31   68  300  342  217   52    0    0    0
     0    0]
 [   0    0    0    0    0    2   12   93  225  388  272   19    0    0
     0    0]
 [   0    0    0    0    0    0    0   10   67  231  559  114    2    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 73.39%
Confussion matrix:
[[1961    0    0    0    0    0    0    0]
 [  78 1681  241    1    0    0    0    0]
 [   0  151 1483  372    0    0    0    0]
 [   0    1  301 1486  170    0    0    0]
 [   0    0    0  229 1408  334    2    0]
 [   0    0    0    4  413 1415  254   15]
 [   0    0    0    0    3  304  894  784]
 [   0    0    0    0    0   72  570 1373]]
Escenario: CMP, Info: Tags
Datos ya disponibles de CMP/data.pickle
500/500 [==============================] - 0s 798us/step - loss: 0.0357 - accuracy: 0.9867


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.67%
Confussion matrix:
[[4010    0    0    0]
 [   1 4085   11    0]
 [   0    5 3841   93]
 [   0    0  103 3851]]
Escenario: CGP, Info: Tags
Datos ya disponibles de CGP/data.pickle
500/500 [==============================] - 0s 857us/step - loss: 0.0355 - accuracy: 0.9879


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 98.79%
Confussion matrix:
[[4082    0    0    0]
 [   1 4055   10    0]
 [   0   16 3800   81]
 [   0    0   85 3870]]
Escenario: SPP, Info: Tags
Datos ya disponibles de SPP/data.pickle
500/500 [==============================] - 0s 802us/step - loss: 0.1091 - accuracy: 0.9546


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 95.46%
Confussion matrix:
[[3942    0    0    0]
 [   0 4116    6    0]
 [   0   13 3562  332]
 [   0    0  375 3654]]
Escenario: IPM, Info: Tags
Datos ya disponibles de IPM/data.pickle
500/500 [==============================] - 0s 804us/step - loss: 0.6905 - accuracy: 0.6799


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 67.99%
Confussion matrix:
[[2052    4    0    0    0    0    0    0]
 [  30 1707  206    0    0    0    0    0]
 [   0  154 1565  271    2    0    0    0]
 [   0    1  434 1313  238    1    0    0]
 [   0    0    3  245 1498  236   15    2]
 [   0    0    0    2  234  787  450  529]
 [   0    0    0    0  161  697  463  699]
 [   0    0    0    0   11  188  309 1493]]
Escenario: CMM, Info: Tags
Datos ya disponibles de CMM/data.pickle
500/500 [==============================] - 0s 802us/step - loss: 0.5501 - accuracy: 0.7517


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 75.17%
Confussion matrix:
[[2018    5    0    0    0    0    0    0]
 [  31 1783  215    0    0    0    0    0]
 [   0  156 1557  288    1    0    0    0]
 [   0    1  410 1423  174    0    0    0]
 [   0    0    0  226 1411  298    3    0]
 [   0    0    0    0  276 1452  273   12]
 [   0    0    0    0    3  278  990  701]
 [   0    0    0    0    0   51  562 1402]]
Escenario: SMG, Info: Tags
Datos ya disponibles de SMG/data.pickle
500/500 [==============================] - 0s 804us/step - loss: 1.1973 - accuracy: 0.4767


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 47.67%
Confussion matrix:
[[1008    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [ 705  272   11    0    0    0    0    0    0    0    0    0    0    0
     0    0]
 [  43  301  433  176    6    0    0    0    0    0    0    0    0    0
     0    0]
 [   0   20  177  528  253   21    0    0    0    0    0    0    0    0
     0    0]
 [   0    1   14  222  457  245   28    3    0    0    0    0    0    0
     0    0]
 [   0    0    1   47  284  445  202   32    3    1    0    0    0    0
     0    0]
 [   0    0    0    1   42  211  408  228   90   16    0    0    0    0
     0    0]
 [   0    0    0    0    3   52  206  294  271  123   13    0    0    0
     0    0]
 [   0    0    0    0    1   11  100  242  365  230   54    0    0    0
     0    0]
 [   0    0    0    0    0    1   11   61  207  395  258   13    0    0
     0    0]
 [   0    0    0    0    0    0    0    3   43  258  563  133    6    0
     0    0]
 [   0    0    0    0    0   

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Accuracy: 75.01%
Confussion matrix:
[[2074    0    0    0    0    0    0    0]
 [  85 1744  122    0    0    0    0    0]
 [   0  215 1365  367    2    0    0    0]
 [   0    4  338 1534  221    0    0    0]
 [   0    0    0  204 1539  281    0    0]
 [   0    0    0    2  285 1360  285   12]
 [   0    0    0    0    3  327 1053  635]
 [   0    0    0    0    0   60  587 1296]]
